version: '3.8'
services:
  serial-listener:
    image: volex/serial-listener
    # volumes:
    #   - /dev/bus:/dev/bus:ro
    #   - /dev/serial:/dev/serial:ro
    network_mode: 'host'
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev:ro
    privileged: true
    device_cgroup_rules:
      - 'c 188:* rmw'
    restart: always

    # environment:
    #   - PORT=/dev/ttyUSB0
